export const registryFieldHelp = {
  accessCode:
    'Código de 12 dígitos que permite consultar a certidão; é enviado só para esta consulta e não é guardado.',
  email: 'Enviado apenas quando o serviço do registo o pedir para abrir a certidão.',
  firma: 'Nome da entidade tal como veio da certidão importada.',
  nipc: 'Identificador NIPC extraído da certidão, quando presente.',
  legalForm: 'Natureza ou forma jurídica normalizada a partir da certidão.',
  matricula: 'Referência de matrícula indicada no registo comercial.',
  sede: 'Sede extraída da certidão; pode ser texto livre ou morada estruturada.',
  dataConstituicao: 'Data de constituição extraída da certidão, quando disponível.',
  capital: 'Capital impresso na certidão, sem cálculo adicional.',
  objeto: 'Objeto ou fim registado conforme texto importado da certidão.',
  cae: 'Atividades económicas da certidão, enriquecidas pelo catálogo CAE quando possível.',
  accessCodeMasked: 'Código ocultado para auditoria; o valor completo nunca é mostrado.',
  retrievedAt: 'Momento em que esta consulta foi executada.',
  conservatoria: 'Conservatória indicada no documento importado.',
  oficial: 'Oficial indicado no documento importado.',
  subscribedOn: 'Data de subscrição indicada na certidão.',
  validUntil: 'Data de validade indicada na certidão; não renova a consulta.',
  source: 'URL usado para obter a certidão nesta importação.',
  digest: 'SHA-256 do HTML importado, para comparar o documento original.',
  naturezaJuridica: 'Natureza jurídica tal como foi lida na inscrição da certidão.',
  fiscalYearEnd: 'Fecho do exercício indicado na inscrição, quando presente.',
  capitalRealization: 'Nota de realização do capital transcrita da certidão.',
  deliberationDate: 'Data da deliberação indicada na inscrição, quando presente.',
  formaObrigar: 'Texto importado sobre quem vincula a entidade.',
} as const;
