//! Build script: enumerate every `assets/*.json` template and emit a manifest of
//! `(id_stem, include_str!(...))` pairs into `$OUT_DIR/asset_manifest.rs`.
//!
//! This is what makes the catalog **data, not code** (t48 extensibility goal): a new template is
//! added by dropping a `.json` file under `assets/` — no Rust edit, no `include_str!` line to
//! maintain by hand. The generated `ASSET_FILES` slice is `include!`d by `lib.rs` and parsed by
//! `load_registry()`. Entries are sorted for deterministic load order.

use std::{env, fs, path::PathBuf};

fn main() {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR");
    let assets_dir = PathBuf::from(&manifest_dir).join("assets");

    // Re-run when a template is added or removed from the directory.
    println!("cargo:rerun-if-changed=assets");

    let mut entries: Vec<(String, String)> = fs::read_dir(&assets_dir)
        .unwrap_or_else(|e| panic!("read assets dir {}: {e}", assets_dir.display()))
        .filter_map(Result::ok)
        .map(|e| e.path())
        .filter(|p| p.extension().map(|x| x == "json").unwrap_or(false))
        .map(|p| {
            let stem = p
                .file_stem()
                .expect("asset file stem")
                .to_string_lossy()
                .into_owned();
            // Forward slashes so the emitted `include_str!` path is valid on Windows too.
            let full = p.to_string_lossy().replace('\\', "/");
            (stem, full)
        })
        .collect();
    entries.sort();

    let mut out = String::from(
        "// @generated by build.rs — do not edit. Lists every embedded template asset.\n\
         pub(crate) static ASSET_FILES: &[(&str, &str)] = &[\n",
    );
    for (stem, full) in &entries {
        out.push_str(&format!("    ({stem:?}, include_str!({full:?})),\n"));
        // Re-run when an existing asset's contents change.
        println!("cargo:rerun-if-changed={full}");
    }
    out.push_str("];\n");

    let out_path = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR")).join("asset_manifest.rs");
    fs::write(&out_path, out).unwrap_or_else(|e| panic!("write {}: {e}", out_path.display()));
}
