//! An offline [`TsaTransport`] that replays a canned `TimeStampResp`.
//!
//! [`MockTsaTransport::from_fixture`] returns the bundled real-world OpenSSL response
//! ([`FIXTURE_RESPONSE_DER`]) so the full build-request -> send -> parse -> verify round-trip runs
//! with no network. See `TESTING.md` for fixture provenance.

use std::sync::Mutex;

use crate::error::TsaError;
use crate::transport::TsaTransport;

/// A real RFC 3161 `TimeStampReq` over the SHA-256 digest of `b"abc"`, nonce
/// `0x314CFCE4E0651827`, `certReq` unset. Pairs with [`FIXTURE_RESPONSE_DER`].
pub const FIXTURE_REQUEST_DER: &[u8] = include_bytes!("../fixtures/openssl_sha256_abc.tsq");

/// A real RFC 3161 `TimeStampResp` (granted) whose token covers the SHA-256 digest of `b"abc"`,
/// echoes nonce `0x314CFCE4E0651827`, and embeds the TSA signing certificate. Generated by OpenSSL
/// `ts`; provenance in `TESTING.md`.
pub const FIXTURE_RESPONSE_DER: &[u8] = include_bytes!("../fixtures/openssl_sha256_abc.tsr");

/// The SHA-256 digest of `b"abc"` — the imprint the bundled fixtures cover.
pub const FIXTURE_DIGEST: [u8; 32] = [
    0xba, 0x78, 0x16, 0xbf, 0x8f, 0x01, 0xcf, 0xea, 0x41, 0x41, 0x40, 0xde, 0x5d, 0xae, 0x22, 0x23,
    0xb0, 0x03, 0x61, 0xa3, 0x96, 0x17, 0x7a, 0x9c, 0xb4, 0x10, 0xff, 0x61, 0xf2, 0x00, 0x15, 0xad,
];

/// The nonce echoed by the bundled fixture response.
pub const FIXTURE_NONCE: u64 = 0x314C_FCE4_E065_1827;

/// A transport that ignores the request and returns a fixed `TimeStampResp`, recording the last
/// request bytes it was handed so tests can assert on the wire request.
#[derive(Debug)]
pub struct MockTsaTransport {
    response: Vec<u8>,
    last_request: Mutex<Option<Vec<u8>>>,
}

impl MockTsaTransport {
    /// A mock that always returns `response_der`.
    pub fn new(response_der: impl Into<Vec<u8>>) -> Self {
        Self {
            response: response_der.into(),
            last_request: Mutex::new(None),
        }
    }

    /// A mock returning the bundled real-world OpenSSL response ([`FIXTURE_RESPONSE_DER`]).
    pub fn from_fixture() -> Self {
        Self::new(FIXTURE_RESPONSE_DER.to_vec())
    }

    /// The request bytes handed to the most recent [`send`](TsaTransport::send), if any.
    pub fn last_request(&self) -> Option<Vec<u8>> {
        self.last_request.lock().expect("mutex poisoned").clone()
    }
}

impl TsaTransport for MockTsaTransport {
    fn send(&self, der_req: &[u8]) -> Result<Vec<u8>, TsaError> {
        *self.last_request.lock().expect("mutex poisoned") = Some(der_req.to_vec());
        Ok(self.response.clone())
    }
}
