//! # chancela-templates — the template catalog engine (t48 / TPL-*, Wave C batch-0)
//!
//! This crate owns the template **catalog as data** and the minijinja prose rendering that turns a
//! record context into a [`chancela_core::DocumentModel`] (the frozen render↔pdf seam, §3.1).
//!
//! The document *structure* — which blocks, in what order, the signature policy (TPL-04), the
//! bound rule pack (TPL-30) — is registry data ([`TemplateSpec`] / [`BlockSpec`]); minijinja fills
//! only the *prose fragments* (the fixed legal boilerplate with `{{ field }}` holes). This keeps
//! compliance in the rule pack, never the template (WFL-31), and lets prose be locale-authored
//! content. **Adding a template is a data drop** (`assets/*.json`) — no Rust code (see the module
//! docs on `BlockSpec` for the schema and the crate log for the authoring guide).
//!
//! ## Pipeline
//!
//! ```text
//! assets/*.json ──build.rs──► ASSET_FILES ──load_registry()──► Registry
//!                                                                  │ .get(id) / .find(family,stage)
//!                                                                  ▼
//!   record ctx (serde_json::Value) ──render(spec, ctx)──► DocumentModel  (the frozen seam)
//! ```
//!
//! ## Determinism
//!
//! Rendering reads no clock and no RNG. `created_at` comes from the context or is left `None`
//! (core supplies it). Output block order follows the spec's block order and array-field order, so
//! the same `spec` + `ctx` always serialize byte-identically (regeneration/re-verification, D3).

use chancela_core::{
    Block, DocumentModel, EntityFamily, KvRow, LifecycleStage, MeetingChannel, Run,
    SignaturePolicyHint, SignatureSlot, VoteRow,
};
use serde::{Deserialize, Serialize};
use serde_json::Value;

// The embedded catalog manifest generated by `build.rs`: `ASSET_FILES: &[(&str, &str)]`
// (asset-stem, file-contents). Regenerated whenever an `assets/*.json` file changes.
include!(concat!(env!("OUT_DIR"), "/asset_manifest.rs"));

// ---------------------------------------------------------------------------------------------
// Registry data types (§3.2) — the runtime shape. `TemplateSpec` derives `Serialize` only (the
// picker DTO / `document.generated` event read it); deserialization goes through the wire DTO
// below because core's `SignaturePolicyHint` is `Serialize`-only.
// ---------------------------------------------------------------------------------------------

/// A registry entry: one template, versioned, binding a family × stage to an ordered block
/// layout (§3.2). `id` carries a version suffix (e.g. `"csc-ata-ag/v1"`); the loader rejects
/// duplicate ids. Recorded verbatim in the `document.generated` ledger event, so a later template
/// edit never changes what a past seal produced (D4).
#[derive(Debug, Clone, PartialEq, Serialize)]
pub struct TemplateSpec {
    /// Stable, versioned id (e.g. `"csc-ata-ag/v1"`). Unique across the registry.
    pub id: String,
    /// The entity family this template serves.
    pub family: EntityFamily,
    /// Where in the book lifecycle this template sits.
    pub stage: LifecycleStage,
    /// The meeting channels this template is valid for.
    pub channels: Vec<MeetingChannel>,
    /// The signature policy hint to prefer for documents rendered from this template (TPL-04).
    pub signature_policy: SignaturePolicyHint,
    /// The compliance rule pack bound to this template (TPL-30); the id, not the pack itself.
    pub rule_pack_id: String,
    /// The ordered block layout that produces the [`DocumentModel`].
    pub blocks: Vec<BlockSpec>,
    /// The locale the prose is authored in (v1: `"pt-PT"`, UX-21).
    pub locale: String,
}

/// One row of a [`BlockSpec::KeyValue`]: `key` and `value` are **minijinja templates** (usually
/// `key` is a literal PT label and `value` interpolates a record field). A row whose `value`
/// renders empty is omitted — this is how optional/absent fields (e.g. a missing NIPC) disappear.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct KvRowSpec {
    /// minijinja template for the row label (left column).
    pub key: String,
    /// minijinja template for the row value (right column).
    pub value: String,
}

/// A block in a [`TemplateSpec`]'s layout. Prose blocks ([`BlockSpec::Heading`],
/// [`BlockSpec::Paragraph`]) carry a **minijinja template string** rendered against the record
/// context. Structural blocks project typed record fields into rows/slots (TPL-03: no free-typing
/// of the generated document).
///
/// ## Asset schema (`assets/*.json`, `kind`-tagged)
///
/// | `kind` | fields | produces |
/// |---|---|---|
/// | `Heading` | `level:u8`, `template` | [`Block::Heading`] (skipped if it renders empty) |
/// | `Paragraph` | `template`, `items?` | one [`Block::Paragraph`] (or one per element of `items`) |
/// | `KeyValue` | `rows:[{key,value}]`, `items?` | [`Block::KeyValue`] (rows repeat per `items` element) |
/// | `VoteTable` | `items`, `label`, `vote_field?="vote"`, `unanimous_total?` | [`Block::VoteTable`] |
/// | `SignatureBlock` | `source`, `role`, `name` | [`Block::SignatureBlock`] |
/// | `PageBreak` / `Rule` | — | the matching marker block |
///
/// `items` / `source` are dotted context paths to an array; a template rendered per element sees
/// the element's fields overlaid on the parent context (so `{{ text }}` binds to the element and
/// `{{ members_present }}` still reaches the record root). **A prose block that renders to only
/// whitespace, and a structural block that yields zero rows/slots, are omitted** — this gives
/// conditional blocks (`{% if channel == 'Telematic' %}…{% endif %}`) and optional sections for
/// free, without a schema-level condition.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(tag = "kind")]
pub enum BlockSpec {
    /// A heading whose text is a minijinja template.
    Heading {
        /// Heading depth, 1-based.
        level: u8,
        /// minijinja template for the heading text (e.g. `"Ata n.º {{ ata_number }}"`).
        template: String,
    },
    /// A paragraph whose text is a minijinja template. When `items` is set, one paragraph is
    /// emitted per array element (each in element+parent scope); otherwise one paragraph.
    Paragraph {
        /// Optional dotted context path to an array; emit one paragraph per element.
        #[serde(default)]
        items: Option<String>,
        /// minijinja template for the paragraph body.
        template: String,
    },
    /// A key/value table. When `items` is set, `rows` repeat once per array element (in
    /// element+parent scope); otherwise `rows` render once against the record root.
    KeyValue {
        /// Optional dotted context path to an array; repeat `rows` per element.
        #[serde(default)]
        items: Option<String>,
        /// The row templates, in order.
        rows: Vec<KvRowSpec>,
    },
    /// The deliberation vote table. Projects each element of `items` into a [`VoteRow`]: the
    /// domain `VoteResult` serialized in `vote_field` becomes `{favor, against, abstain}`
    /// (`Recorded` → its counts; `Unanimous` → `favor = unanimous_total` if given, else 0).
    /// Elements with no recorded vote are skipped.
    VoteTable {
        /// Dotted context path to the deliberations array (e.g. `"deliberation_items"`).
        items: String,
        /// minijinja template for each row's label (element+parent scope).
        label: String,
        /// Field within each element carrying the serialized `VoteResult`.
        #[serde(default = "default_vote_field")]
        vote_field: String,
        /// minijinja template (→ integer) for the favour count when a vote is `Unanimous`.
        #[serde(default)]
        unanimous_total: Option<String>,
    },
    /// The signature block. Projects each element of `source` into a [`SignatureSlot`] using the
    /// `role` and `name` templates (element+parent scope). Slots that render fully empty are
    /// skipped; a source with no elements omits the block.
    SignatureBlock {
        /// Dotted context path to the signatory array (e.g. `"signatories"`).
        source: String,
        /// minijinja template for each slot's role label (e.g. `"{{ capacity | role_label }}"`).
        role: String,
        /// minijinja template for each slot's signatory name.
        name: String,
    },
    /// A forced page break.
    PageBreak,
    /// A horizontal rule.
    Rule,
}

fn default_vote_field() -> String {
    "vote".to_string()
}

// ---------------------------------------------------------------------------------------------
// Wire DTO (deserialization). `TemplateSpec` cannot derive `Deserialize` because core's
// `SignaturePolicyHint` is `Serialize`-only (e0's flagged gap). We own a local mirror of that one
// field and convert into the runtime `TemplateSpec`. Every other field either is a primitive or a
// core type that already derives `Deserialize` (`EntityFamily`, `MeetingChannel`,
// `LifecycleStage`), and `BlockSpec` derives it directly.
// ---------------------------------------------------------------------------------------------

/// Local, `Deserialize`-able mirror of [`chancela_core::SignaturePolicyHint`] (which is
/// `Serialize`-only). Variant names match the core enum verbatim so the asset JSON reads
/// naturally (`"signature_policy": "QualifiedPreferred"`).
#[derive(Debug, Clone, Copy, PartialEq, Deserialize)]
enum SignaturePolicyDto {
    QualifiedPreferred,
    QualifiedOrHandwritten,
    ManualAttested,
}

impl From<SignaturePolicyDto> for SignaturePolicyHint {
    fn from(dto: SignaturePolicyDto) -> Self {
        match dto {
            SignaturePolicyDto::QualifiedPreferred => SignaturePolicyHint::QualifiedPreferred,
            SignaturePolicyDto::QualifiedOrHandwritten => {
                SignaturePolicyHint::QualifiedOrHandwritten
            }
            SignaturePolicyDto::ManualAttested => SignaturePolicyHint::ManualAttested,
        }
    }
}

/// The on-disk asset shape. Deserialized from an `assets/*.json` file, then converted into the
/// runtime [`TemplateSpec`]. `#[serde(deny_unknown_fields)]` so a typo in an asset is a load-time
/// error, not a silently-ignored field.
#[derive(Debug, Clone, Deserialize)]
#[serde(deny_unknown_fields)]
struct TemplateSpecDto {
    id: String,
    family: EntityFamily,
    stage: LifecycleStage,
    channels: Vec<MeetingChannel>,
    signature_policy: SignaturePolicyDto,
    rule_pack_id: String,
    blocks: Vec<BlockSpec>,
    locale: String,
}

impl From<TemplateSpecDto> for TemplateSpec {
    fn from(dto: TemplateSpecDto) -> Self {
        TemplateSpec {
            id: dto.id,
            family: dto.family,
            stage: dto.stage,
            channels: dto.channels,
            signature_policy: dto.signature_policy.into(),
            rule_pack_id: dto.rule_pack_id,
            blocks: dto.blocks,
            locale: dto.locale,
        }
    }
}

// ---------------------------------------------------------------------------------------------
// Registry + loader
// ---------------------------------------------------------------------------------------------

/// The loaded, validated template catalog. Holds the specs keyed by id (id-uniqueness enforced at
/// load), with lookup by id and filter by (family, stage).
#[derive(Debug, Clone, Default)]
pub struct Registry {
    specs: Vec<TemplateSpec>,
}

impl Registry {
    /// All specs, in load order (sorted by asset filename — deterministic).
    pub fn specs(&self) -> &[TemplateSpec] {
        &self.specs
    }

    /// Look a spec up by its versioned id.
    pub fn get(&self, id: &str) -> Option<&TemplateSpec> {
        self.specs.iter().find(|s| s.id == id)
    }

    /// All specs matching a (family, stage) — the template picker's filter (`GET /v1/templates`).
    pub fn find(&self, family: EntityFamily, stage: LifecycleStage) -> Vec<&TemplateSpec> {
        self.specs
            .iter()
            .filter(|s| s.family == family && s.stage == stage)
            .collect()
    }
}

/// Errors from loading the embedded template registry.
#[derive(Debug, thiserror::Error)]
pub enum RegistryError {
    /// Two specs declared the same id (§3.2: the loader rejects duplicates).
    #[error("duplicate template id: {0}")]
    DuplicateId(String),
    /// An embedded asset failed to parse.
    #[error("failed to parse template asset {asset}: {source}")]
    Asset {
        /// The offending asset name (file stem).
        asset: String,
        /// The underlying parse error.
        #[source]
        source: serde_json::Error,
    },
}

/// Errors from rendering a [`TemplateSpec`] into a [`DocumentModel`].
#[derive(Debug, thiserror::Error)]
pub enum RenderError {
    /// A minijinja template failed to render (bad syntax or a strict-mode miss).
    #[error("template render failed: {0}")]
    Template(String),
    /// The record context was missing a field the renderer required (e.g. the document title).
    #[error("missing context field: {0}")]
    MissingField(String),
}

/// Load the embedded template catalog (§3.2): parse every `assets/*.json`, reject duplicate ids,
/// return the [`Registry`].
pub fn load_registry() -> Result<Registry, RegistryError> {
    registry_from(ASSET_FILES)
}

/// Build a registry from an explicit `(asset_name, json)` list. Factored out of [`load_registry`]
/// so tests can exercise duplicate-id rejection without shipping a broken asset.
fn registry_from(assets: &[(&str, &str)]) -> Result<Registry, RegistryError> {
    let mut specs: Vec<TemplateSpec> = Vec::with_capacity(assets.len());
    for (name, json) in assets {
        let dto: TemplateSpecDto =
            serde_json::from_str(json).map_err(|source| RegistryError::Asset {
                asset: (*name).to_string(),
                source,
            })?;
        let spec: TemplateSpec = dto.into();
        if specs.iter().any(|s| s.id == spec.id) {
            return Err(RegistryError::DuplicateId(spec.id));
        }
        specs.push(spec);
    }
    Ok(Registry { specs })
}

// ---------------------------------------------------------------------------------------------
// Rendering
// ---------------------------------------------------------------------------------------------

/// Render a [`TemplateSpec`] against a record context into the frozen [`DocumentModel`] seam.
///
/// `ctx` is the record(s) serialized to JSON (as `chancela-api` produces via
/// `serde_json::to_value` + derived helpers). The renderer reads these **reserved metadata keys**
/// for the document envelope, everything else is referenced by the block templates:
///
/// - `entity.name` → [`DocumentModel::entity_name`], `entity.nipc` → [`DocumentModel::entity_nipc`]
/// - `title` → [`DocumentModel::title`] (**required**), `subject` → [`DocumentModel::subject`]
///   (falls back to `title`)
/// - `created_at` → [`DocumentModel::created_at`] (ISO-8601; the caller supplies it — core reads
///   no clock)
///
/// minijinja filters registered for authors: `long_date` (`"2026-07-08"` → `"8 de julho de
/// 2026"`), `channel_label` (`MeetingChannel` name → PT label), `role_label`
/// ([`chancela_core::SignatoryCapacity`] name → PT role label). Built-in filters (`join`, …) are
/// available too.
pub fn render(spec: &TemplateSpec, ctx: &Value) -> Result<DocumentModel, RenderError> {
    let env = build_env();

    let title = ctx
        .get("title")
        .and_then(Value::as_str)
        .ok_or_else(|| RenderError::MissingField("title".to_string()))?
        .to_string();
    let subject = ctx
        .get("subject")
        .and_then(Value::as_str)
        .unwrap_or(&title)
        .to_string();
    let entity_name = ctx
        .pointer("/entity/name")
        .and_then(Value::as_str)
        .unwrap_or("")
        .to_string();
    let entity_nipc = ctx
        .pointer("/entity/nipc")
        .and_then(Value::as_str)
        .map(str::to_string);
    let created_at = ctx
        .get("created_at")
        .and_then(Value::as_str)
        .map(str::to_string);

    let mut doc = DocumentModel {
        title,
        entity_name,
        entity_nipc,
        subject,
        language: spec.locale.clone(),
        created_at,
        blocks: Vec::new(),
    };

    for block in &spec.blocks {
        render_block(&env, block, ctx, &mut doc.blocks)?;
    }

    Ok(doc)
}

/// Assemble the minijinja environment with the author-facing filters. Kept per-call so rendering
/// is stateless and thread-safe; the templates are tiny so compilation cost is negligible.
fn build_env() -> minijinja::Environment<'static> {
    let mut env = minijinja::Environment::new();
    env.add_filter("long_date", long_date);
    env.add_filter("channel_label", channel_label);
    env.add_filter("role_label", role_label);
    env
}

fn render_block(
    env: &minijinja::Environment<'_>,
    block: &BlockSpec,
    ctx: &Value,
    out: &mut Vec<Block>,
) -> Result<(), RenderError> {
    match block {
        BlockSpec::Heading { level, template } => {
            let text = render_str(env, template, ctx)?;
            if !text.trim().is_empty() {
                out.push(Block::Heading {
                    level: *level,
                    text,
                });
            }
        }
        BlockSpec::Paragraph {
            items: None,
            template,
        } => {
            push_paragraph(env, template, ctx, out)?;
        }
        BlockSpec::Paragraph {
            items: Some(path),
            template,
        } => {
            for item in array_at(ctx, path) {
                let scope = merge_scope(ctx, item);
                push_paragraph(env, template, &scope, out)?;
            }
        }
        BlockSpec::KeyValue { items: None, rows } => {
            let kvrows = render_kv_rows(env, rows, ctx)?;
            if !kvrows.is_empty() {
                out.push(Block::KeyValue { rows: kvrows });
            }
        }
        BlockSpec::KeyValue {
            items: Some(path),
            rows,
        } => {
            let mut kvrows = Vec::new();
            for item in array_at(ctx, path) {
                let scope = merge_scope(ctx, item);
                kvrows.extend(render_kv_rows(env, rows, &scope)?);
            }
            if !kvrows.is_empty() {
                out.push(Block::KeyValue { rows: kvrows });
            }
        }
        BlockSpec::VoteTable {
            items,
            label,
            vote_field,
            unanimous_total,
        } => {
            let mut vrows = Vec::new();
            for item in array_at(ctx, items) {
                let vote = item.get(vote_field);
                let scope = merge_scope(ctx, item);
                if let Some(row) =
                    project_vote(env, label, vote, unanimous_total.as_deref(), &scope)?
                {
                    vrows.push(row);
                }
            }
            if !vrows.is_empty() {
                out.push(Block::VoteTable { rows: vrows });
            }
        }
        BlockSpec::SignatureBlock { source, role, name } => {
            let mut slots = Vec::new();
            for item in array_at(ctx, source) {
                let scope = merge_scope(ctx, item);
                let role = render_str(env, role, &scope)?;
                let name = render_str(env, name, &scope)?;
                if role.trim().is_empty() && name.trim().is_empty() {
                    continue;
                }
                slots.push(SignatureSlot { role, name });
            }
            if !slots.is_empty() {
                out.push(Block::SignatureBlock { slots });
            }
        }
        BlockSpec::PageBreak => out.push(Block::PageBreak),
        BlockSpec::Rule => out.push(Block::Rule),
    }
    Ok(())
}

fn push_paragraph(
    env: &minijinja::Environment<'_>,
    template: &str,
    scope: &Value,
    out: &mut Vec<Block>,
) -> Result<(), RenderError> {
    let text = render_str(env, template, scope)?;
    if text.trim().is_empty() {
        return Ok(());
    }
    // v1 emits a single unstyled run per paragraph; inline bold/italic markup is a future
    // enhancement (the seam already carries `Run{bold,italic}` so it is additive).
    out.push(Block::Paragraph {
        runs: vec![Run {
            text,
            bold: false,
            italic: false,
        }],
    });
    Ok(())
}

fn render_kv_rows(
    env: &minijinja::Environment<'_>,
    rows: &[KvRowSpec],
    scope: &Value,
) -> Result<Vec<KvRow>, RenderError> {
    let mut out = Vec::new();
    for r in rows {
        let value = render_str(env, &r.value, scope)?;
        if value.trim().is_empty() {
            continue; // optional/absent field → omit the row
        }
        let key = render_str(env, &r.key, scope)?;
        out.push(KvRow { key, value });
    }
    Ok(out)
}

/// Project a serialized `VoteResult` into a [`VoteRow`]. Returns `None` when the element carries
/// no vote (so a deliberation with no recorded tally produces no table row).
fn project_vote(
    env: &minijinja::Environment<'_>,
    label_tmpl: &str,
    vote: Option<&Value>,
    unanimous_total: Option<&str>,
    scope: &Value,
) -> Result<Option<VoteRow>, RenderError> {
    let vote = match vote {
        Some(v) if !v.is_null() => v,
        _ => return Ok(None),
    };
    let label = render_str(env, label_tmpl, scope)?;

    // `VoteResult` is externally tagged: `Unanimous` → the string "Unanimous";
    // `Recorded{..}` → `{"Recorded": {"em_favor":_, "contra":_, "abstencoes":_}}`.
    let (favor, against, abstain) = if vote.as_str() == Some("Unanimous") {
        let total = match unanimous_total {
            Some(t) => render_str(env, t, scope)?
                .trim()
                .parse::<u32>()
                .unwrap_or(0),
            None => 0,
        };
        (total, 0, 0)
    } else if let Some(rec) = vote.get("Recorded") {
        let count = |k: &str| rec.get(k).and_then(Value::as_u64).unwrap_or(0) as u32;
        (count("em_favor"), count("contra"), count("abstencoes"))
    } else {
        (0, 0, 0)
    };

    Ok(Some(VoteRow {
        label,
        favor,
        against,
        abstain,
    }))
}

/// Render a template string against a JSON scope, mapping any minijinja error into
/// [`RenderError::Template`] with the full error chain.
fn render_str(
    env: &minijinja::Environment<'_>,
    src: &str,
    scope: &Value,
) -> Result<String, RenderError> {
    env.render_str(src, scope)
        .map_err(|e| RenderError::Template(format!("{e:#}")))
}

/// Follow a dotted path (`"a.b"`) to an array in `ctx`; return its elements, or empty if the path
/// is absent or not an array.
fn array_at<'a>(ctx: &'a Value, path: &str) -> Vec<&'a Value> {
    let mut cur = ctx;
    for seg in path.split('.') {
        match cur.get(seg) {
            Some(v) => cur = v,
            None => return Vec::new(),
        }
    }
    cur.as_array()
        .map(|a| a.iter().collect())
        .unwrap_or_default()
}

/// Overlay an array element's fields on the parent context so a per-element template can read both
/// the element (`{{ text }}`) and the record root (`{{ members_present }}`). The element wins on a
/// key clash.
fn merge_scope(parent: &Value, item: &Value) -> Value {
    match (parent.as_object(), item.as_object()) {
        (Some(p), Some(i)) => {
            let mut m = p.clone();
            for (k, v) in i {
                m.insert(k.clone(), v.clone());
            }
            Value::Object(m)
        }
        _ => item.clone(),
    }
}

// --- author-facing minijinja filters (reusable helpers, not per-template code) ----------------

/// `"2026-07-08"` → `"8 de julho de 2026"`. Passes the input through unchanged if it is not a
/// `YYYY-MM-DD` date, so it is safe on already-formatted or empty values.
fn long_date(value: String) -> String {
    const MESES: [&str; 12] = [
        "janeiro",
        "fevereiro",
        "março",
        "abril",
        "maio",
        "junho",
        "julho",
        "agosto",
        "setembro",
        "outubro",
        "novembro",
        "dezembro",
    ];
    let parts: Vec<&str> = value.split('-').collect();
    if parts.len() == 3 {
        if let (Ok(y), Ok(m), Ok(d)) = (
            parts[0].parse::<i32>(),
            parts[1].parse::<usize>(),
            parts[2].parse::<u32>(),
        ) {
            if (1..=12).contains(&m) {
                return format!("{d} de {} de {y}", MESES[m - 1]);
            }
        }
    }
    value
}

/// [`chancela_core::MeetingChannel`] serialized name → PT label.
fn channel_label(value: String) -> String {
    match value.as_str() {
        "Physical" => "Presencial",
        "Hybrid" => "Híbrida (presencial e telemática)",
        "Telematic" => "Telemática",
        "WrittenResolution" => "Deliberação unânime por escrito",
        other => other,
    }
    .to_string()
}

/// [`chancela_core::SignatoryCapacity`] serialized name → PT role label.
fn role_label(value: String) -> String {
    match value.as_str() {
        "Chair" => "Presidente da mesa",
        "Secretary" => "Secretário",
        "Member" => "Membro",
        "Manager" => "Gerente",
        "Administrator" => "Administrador",
        "Attorney" => "Mandatário",
        "CondoOwner" => "Condómino",
        other => other,
    }
    .to_string()
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    /// An `Act`-shaped render context for `csc-ata-ag/v1`. This is the exact shape
    /// `chancela-api` (e5) produces: `serde_json::to_value(&act)` fields + an `entity` object +
    /// the reserved `title`/`subject`/`created_at` envelope keys. Uses the fictional example
    /// entity "Encosto Estratégico Lda" / people "Amélia Marques" et al.
    fn ata_ctx() -> Value {
        json!({
            "title": "Ata n.º 1 — Assembleia Geral Ordinária",
            "subject": "Assembleia geral ordinária de Encosto Estratégico Lda",
            "created_at": "2026-07-08T10:30:00Z",
            "entity": {
                "name": "Encosto Estratégico Lda",
                "nipc": "515202030",
                "seat": "Rua das Amoreiras, n.º 12, 1250-020 Lisboa"
            },
            "ata_number": 1,
            "meeting_date": "2026-07-08",
            "meeting_time": "15:00",
            "place": "sede social, em Lisboa",
            "channel": "Physical",
            "mesa": { "presidente": "Amélia Marques", "secretarios": ["Bruno Cardoso"] },
            "members_present": 3,
            "members_represented": 1,
            "attendance_reference": "Lista de presenças anexa (Anexo I)",
            "telematic_evidence": null,
            "agenda": [
                { "number": 1, "text": "Aprovação do relatório de gestão e das contas do exercício de 2025." },
                { "number": 2, "text": "Aplicação de resultados." }
            ],
            "deliberation_items": [
                {
                    "agenda_number": 1,
                    "text": "Aprovar o relatório de gestão e as contas do exercício de 2025.",
                    "vote": { "Recorded": { "em_favor": 3, "contra": 1, "abstencoes": 0 } },
                    "statements": [
                        { "member": "Carla Nunes", "text": "Vota contra por discordar da política de amortizações." }
                    ]
                },
                {
                    "agenda_number": 2,
                    "text": "Transitar o resultado líquido para reservas livres.",
                    "vote": "Unanimous",
                    "statements": []
                }
            ],
            "referenced_documents": [
                { "label": "Relatório de gestão 2025", "reference": "Anexo II" }
            ],
            "signatories": [
                { "name": "Amélia Marques", "capacity": "Chair", "signed": true, "permilage": null },
                { "name": "Bruno Cardoso", "capacity": "Secretary", "signed": false, "permilage": null }
            ]
        })
    }

    fn ata_spec() -> TemplateSpec {
        let reg = load_registry().expect("registry loads");
        reg.get("csc-ata-ag/v1")
            .expect("csc-ata-ag/v1 present")
            .clone()
    }

    #[test]
    fn registry_loads_and_indexes_the_spine_template() {
        let reg = load_registry().expect("registry loads");
        let spec = reg.get("csc-ata-ag/v1").expect("spine present");
        assert_eq!(spec.family, EntityFamily::CommercialCompany);
        assert_eq!(spec.stage, LifecycleStage::Ata);
        assert_eq!(spec.rule_pack_id, "csc-art63/v2");
        assert_eq!(
            spec.signature_policy,
            SignaturePolicyHint::QualifiedPreferred
        );
        assert_eq!(spec.locale, "pt-PT");
        // Filter by (family, stage) surfaces it.
        let found = reg.find(EntityFamily::CommercialCompany, LifecycleStage::Ata);
        assert!(found.iter().any(|s| s.id == "csc-ata-ag/v1"));
    }

    #[test]
    fn loader_rejects_duplicate_ids() {
        let one = r#"{"id":"dup/v1","family":"Association","stage":"Ata","channels":[],
            "signature_policy":"ManualAttested","rule_pack_id":"x","locale":"pt-PT","blocks":[]}"#;
        let err = registry_from(&[("a", one), ("b", one)]).unwrap_err();
        assert!(matches!(err, RegistryError::DuplicateId(id) if id == "dup/v1"));
    }

    #[test]
    fn renders_the_expected_block_structure() {
        let doc = render(&ata_spec(), &ata_ctx()).expect("render ok");

        // Envelope metadata from the reserved ctx keys.
        assert_eq!(doc.title, "Ata n.º 1 — Assembleia Geral Ordinária");
        assert_eq!(doc.entity_name, "Encosto Estratégico Lda");
        assert_eq!(doc.entity_nipc.as_deref(), Some("515202030"));
        assert_eq!(doc.language, "pt-PT");
        assert_eq!(doc.created_at.as_deref(), Some("2026-07-08T10:30:00Z"));

        // Heading L1 "Ata n.º 1" and the two section headings are present.
        let headings: Vec<(u8, &str)> = doc
            .blocks
            .iter()
            .filter_map(|b| match b {
                Block::Heading { level, text } => Some((*level, text.as_str())),
                _ => None,
            })
            .collect();
        assert!(headings.contains(&(1, "Ata n.º 1")));
        assert!(headings.contains(&(2, "Ordem de trabalhos")));
        assert!(headings.contains(&(2, "Deliberações")));

        // The header KeyValue formatted the date via the `long_date` filter.
        let has_long_date = doc.blocks.iter().any(|b| {
            matches!(b, Block::KeyValue { rows }
                if rows.iter().any(|r| r.key == "Data" && r.value == "8 de julho de 2026"))
        });
        assert!(has_long_date, "expected long-date formatted 'Data' row");

        // VoteTable: one row per deliberation. Recorded → its counts; Unanimous → favour =
        // members_present + members_represented (3 + 1 = 4).
        let vote_rows = doc
            .blocks
            .iter()
            .find_map(|b| match b {
                Block::VoteTable { rows } => Some(rows),
                _ => None,
            })
            .expect("a vote table");
        assert_eq!(vote_rows.len(), 2);
        assert_eq!(
            (
                vote_rows[0].favor,
                vote_rows[0].against,
                vote_rows[0].abstain
            ),
            (3, 1, 0)
        );
        assert_eq!(
            (
                vote_rows[1].favor,
                vote_rows[1].against,
                vote_rows[1].abstain
            ),
            (4, 0, 0)
        );

        // SignatureBlock: two slots, capacities mapped to PT role labels.
        let slots = doc
            .blocks
            .iter()
            .find_map(|b| match b {
                Block::SignatureBlock { slots } => Some(slots),
                _ => None,
            })
            .expect("a signature block");
        assert_eq!(slots.len(), 2);
        assert_eq!(slots[0].role, "Presidente da mesa");
        assert_eq!(slots[0].name, "Amélia Marques");
        assert_eq!(slots[1].role, "Secretário");

        // The referenced-documents KeyValue rendered (loop over a non-empty array).
        let has_ref_doc = doc.blocks.iter().any(|b| {
            matches!(b, Block::KeyValue { rows }
                if rows.iter().any(|r| r.key == "Relatório de gestão 2025"))
        });
        assert!(has_ref_doc, "expected referenced-documents row");
    }

    #[test]
    fn conditional_telematic_block_is_omitted_for_physical_meetings() {
        let doc = render(&ata_spec(), &ata_ctx()).expect("render ok");
        // Channel is Physical, so the art. 377.º evidence paragraph renders empty and is dropped.
        let mentions_377 = doc.blocks.iter().any(|b| match b {
            Block::Paragraph { runs } => runs.iter().any(|r| r.text.contains("377.º")),
            _ => false,
        });
        assert!(
            !mentions_377,
            "telematic recital must not appear for Physical"
        );
    }

    #[test]
    fn conditional_telematic_block_appears_for_telematic_meetings() {
        let mut ctx = ata_ctx();
        ctx["channel"] = json!("Telematic");
        ctx["telematic_evidence"] = json!("Reunião por videoconferência com gravação integral.");
        let doc = render(&ata_spec(), &ctx).expect("render ok");
        let mentions_377 = doc.blocks.iter().any(|b| match b {
            Block::Paragraph { runs } => runs.iter().any(|r| r.text.contains("377.º")),
            _ => false,
        });
        assert!(mentions_377, "telematic recital must appear for Telematic");
    }

    #[test]
    fn missing_title_is_a_render_error() {
        let mut ctx = ata_ctx();
        ctx.as_object_mut().unwrap().remove("title");
        let err = render(&ata_spec(), &ctx).unwrap_err();
        assert!(matches!(err, RenderError::MissingField(f) if f == "title"));
    }

    #[test]
    fn rendering_is_deterministic() {
        let spec = ata_spec();
        let ctx = ata_ctx();
        let a = serde_json::to_string(&render(&spec, &ctx).unwrap()).unwrap();
        let b = serde_json::to_string(&render(&spec, &ctx).unwrap()).unwrap();
        assert_eq!(a, b, "same spec + ctx must serialize byte-identically");
    }
}
