//! Journey (t48-e7, Wave C batch-4 — the acceptance capstone): prove the whole document pipeline
//! end-to-end through the **real** composed server binary, then verify the generated bytes are
//! structurally PDF/A-2u conformant.
//!
//! This complements `e2e_books_acts_seal.rs` (e5 asserts the seal's `document` block, a
//! `document.generated` event, and the DOC-03 bundle inline in the seal lifecycle). Here we cover
//! the FULL retrieval surface over the wire and the conformance of the served bytes:
//!
//! - bootstrap → entity → **open book** (assert the termo `document.generated` event + a persisted
//!   book document downloadable as real `application/pdf`);
//! - draft → fill → advance → **seal**, and then assert:
//!   (a) a `document.generated` ledger event exists **for the act** (scope carries `act:{id}`);
//!   (b) `GET /v1/acts/{id}/document` returns real `application/pdf` bytes (200, not 404);
//!   (c) `SealResponse.document` carries `{id, pdf_digest, template_id}` and the digest is the
//!   sha-256 of the fetched bytes;
//!   (d) `GET /v1/acts/{id}/document/preview` returns a well-formed `DocumentModel` JSON pre- AND
//!   post-seal;
//!   (e) the DOC-03 `bundle` endpoint returns the reserved `validation_report: null` shape;
//!   (f) `GET /v1/templates` (bare and `?family=&stage=` filtered) lists the spine templates.
//! - **PDF/A-2u structural conformance** on the bytes the running server served — re-implemented
//!   here (chancela_doc's `selfcheck` is `mod`-private, not exported, so we cannot reuse it as a
//!   single source of truth without touching a crate outside this test lock; we mirror its
//!   invariants over the wire bytes via a `lopdf` dev-dep).
//! - **Service-level determinism:** a second, independent server sealing an equivalent record
//!   yields the *same* `pdf_digest` (the writer reads no clock; `created_at` derives from the frozen
//!   meeting date), proving regeneration/re-verification (plan D3/§164) over the real service.
//!
//! ## External veraPDF gate (documented, NOT CI-required)
//!
//! The Rust structural check below is the automated gate (no native binary, distroless ethos). For
//! a full ISO-19005-2 pass, dump a sealed PDF and run veraPDF out of band:
//!
//! ```text
//! curl -s http://127.0.0.1:PORT/v1/acts/ACT_ID/document -o ata.pdf
//! verapdf -f 2u ata.pdf          # exit 0 == PDF/A-2U conformant
//! verapdf -f 2u --format mrr ata.pdf   # machine-readable report
//! ```
//!
//! Caveat (t48-e2): the AP-less zero-rect signature Widget a strict veraPDF run may flag applies to
//! a **signed** file (Wave D / PAdES) — out of scope here. This journey verifies the **unsigned**
//! generated PDF/A-2u, exactly what `chancela_doc` produces and `chancela-pades` later appends to.

mod common;

use common::*;
use lopdf::{Document, Object};
use serde_json::{Value, json};
use sha2::{Digest, Sha256};

/// Fetch raw bytes (not JSON) from the running server: `(status, content_type, body)`. The harness
/// JSON helpers would panic trying to parse PDF bytes, so the PDF endpoints use their own client.
async fn get_bytes(h: &ServerHarness, path: &str) -> (u16, String, Vec<u8>) {
    let client = reqwest::Client::new();
    let resp = client
        .get(format!("{}{}", h.base_url, path))
        .send()
        .await
        .unwrap_or_else(|e| panic!("GET {path} failed: {e}"));
    let status = resp.status().as_u16();
    let ctype = resp
        .headers()
        .get(reqwest::header::CONTENT_TYPE)
        .and_then(|v| v.to_str().ok())
        .unwrap_or("")
        .to_owned();
    let bytes = resp
        .bytes()
        .await
        .unwrap_or_else(|e| panic!("read body of {path} failed: {e}"))
        .to_vec();
    (status, ctype, bytes)
}

/// Lowercase hex of a sha-256 digest — mirrors the api's `pdf_digest` encoding.
fn sha256_hex(bytes: &[u8]) -> String {
    let digest: [u8; 32] = Sha256::digest(bytes).into();
    digest.iter().map(|b| format!("{b:02x}")).collect()
}

/// Run the shared spine journey (session → CSC entity → book → drafted+filled+advanced act) and
/// return `(session_token, entity_id, book_id, act_id)`. Deterministic inputs so two independent
/// servers produce byte-identical documents.
async fn spine_up_to_signing(h: &ServerHarness) -> (String, String, String, String) {
    let token = bootstrap_session(h).await;
    let entity_id = create_entity(
        h,
        "Encosto Estratégico, S.A.",
        "503004642",
        "Lisboa",
        "SociedadeAnonima",
        &token,
    )
    .await;
    let book_id = open_book(h, &entity_id, &token).await;
    let act_id = draft_act(h, &book_id, "Ata da Assembleia Geral Anual", Some(&token)).await;
    fill_act_contents(h, &act_id, &token).await;
    advance_to_signing(h, &act_id, Some(&token)).await;
    (token, entity_id, book_id, act_id)
}

/// Assert `bytes` are structurally PDF/A-2u conformant — a faithful re-implementation of
/// `chancela_doc::selfcheck::verify` (which is crate-private) over the bytes the server served.
/// Panics with a descriptive message on the first violated invariant.
fn assert_pdfa2u_conformant(bytes: &[u8]) {
    // Header + PDF/A binary marker (a comment line with a byte > 127).
    assert!(
        bytes.starts_with(b"%PDF-1.7"),
        "served PDF header is not %PDF-1.7"
    );
    assert!(
        bytes.get(9..16).is_some_and(|w| w.iter().any(|&b| b > 127)),
        "served PDF missing the PDF/A binary header marker (byte > 127)"
    );

    // Classic xref table (the pades-compatible byte-shape), never an xref stream.
    assert!(
        find(bytes, b"\nxref\n"),
        "no classic `xref` table (an xref stream would break pades)"
    );
    match last_startxref(bytes) {
        Some(off) if bytes.get(off..off + 4) == Some(b"xref") => {}
        _ => panic!("startxref does not resolve to a classic `xref` table"),
    }
    assert!(
        !find(bytes, b"/LZWDecode"),
        "LZWDecode filter is prohibited in PDF/A"
    );

    // Parse and check the object graph.
    let doc = Document::load_mem(bytes).expect("served PDF parses via lopdf");
    assert!(
        !doc.trailer.has(b"Encrypt"),
        "trailer carries /Encrypt (encryption prohibited)"
    );
    let root_id = doc
        .trailer
        .get(b"Root")
        .and_then(Object::as_reference)
        .expect("trailer has a /Root reference");
    let id_arr = doc
        .trailer
        .get(b"ID")
        .and_then(Object::as_array)
        .expect("trailer /ID is a 2-element array");
    assert_eq!(id_arr.len(), 2, "/ID must have two elements");
    let s0 = id_arr[0].as_str().expect("/ID[0] is a string");
    let s1 = id_arr[1].as_str().expect("/ID[1] is a string");
    assert!(
        s0.len() == 16 && s1 == s0,
        "/ID must be two equal 16-byte strings"
    );

    let catalog = doc
        .get_object(root_id)
        .and_then(Object::as_dict)
        .expect("catalog object present");
    assert!(
        !catalog.has(b"AcroForm"),
        "catalog has /AcroForm (must be absent; pades adds it)"
    );
    assert!(
        !catalog.has(b"AA"),
        "catalog has /AA additional-actions (prohibited)"
    );
    assert!(catalog.has(b"Metadata"), "catalog has no /Metadata");
    let oi_arr = catalog
        .get(b"OutputIntents")
        .and_then(Object::as_array)
        .expect("catalog has an /OutputIntents array");
    assert!(!oi_arr.is_empty(), "/OutputIntents is empty");

    // XMP metadata: uncompressed, carrying the PDF/A part+conformance markers.
    let meta_ref = catalog
        .get(b"Metadata")
        .and_then(Object::as_reference)
        .expect("/Metadata is an indirect reference");
    let meta = doc
        .get_object(meta_ref)
        .and_then(Object::as_stream)
        .expect("/Metadata is a stream");
    assert!(
        !meta.dict.has(b"Filter"),
        "/Metadata stream is compressed (must be plaintext, no /Filter)"
    );
    assert!(
        find(&meta.content, b"<pdfaid:part>2</pdfaid:part>"),
        "XMP missing pdfaid:part = 2"
    );
    assert!(
        find(&meta.content, b"<pdfaid:conformance>U</pdfaid:conformance>"),
        "XMP missing pdfaid:conformance = U"
    );

    // OutputIntent: GTS_PDFA1 with an N=3 (RGB) DestOutputProfile.
    let oi_ref = oi_arr[0]
        .as_reference()
        .expect("OutputIntent is an indirect reference");
    let oi = doc
        .get_object(oi_ref)
        .and_then(Object::as_dict)
        .expect("OutputIntent object present");
    assert_eq!(
        oi.get(b"S").and_then(Object::as_name).ok(),
        Some(b"GTS_PDFA1".as_ref()),
        "OutputIntent /S is not /GTS_PDFA1"
    );
    let icc_ref = oi
        .get(b"DestOutputProfile")
        .and_then(Object::as_reference)
        .expect("OutputIntent has a /DestOutputProfile ref");
    let icc = doc
        .get_object(icc_ref)
        .and_then(Object::as_stream)
        .expect("/DestOutputProfile is a stream");
    assert_eq!(
        icc.dict.get(b"N").and_then(Object::as_i64).ok(),
        Some(3),
        "ICC profile stream /N is not 3"
    );

    // Every text font: an embedded program + a /ToUnicode CMap (the "u" of PDF/A-2u).
    assert_fonts_embedded(&doc);

    // First page /Annots (pades C3): absent or an inline array.
    if let Some(first_page) = doc.page_iter().next() {
        let page = doc
            .get_object(first_page)
            .and_then(Object::as_dict)
            .expect("first page object present");
        match page.get(b"Annots") {
            Ok(Object::Array(_)) | Err(_) => {}
            Ok(_) => panic!("first page /Annots is not an inline array"),
        }
    }
}

/// Every font on every page must embed its program (`/FontFile2`|`/FontFile3`) and carry a
/// `/ToUnicode` CMap. Mirrors `chancela_doc::selfcheck::verify_fonts`.
fn assert_fonts_embedded(doc: &Document) {
    for page_id in doc.page_iter() {
        let Ok(fonts) = doc.get_page_fonts(page_id) else {
            continue;
        };
        for (_name, font) in fonts {
            let subtype = font.get(b"Subtype").and_then(Object::as_name).ok();
            assert!(
                font.has(b"ToUnicode"),
                "a text font has no /ToUnicode CMap (breaks the \"u\")"
            );
            let descriptor = if subtype == Some(b"Type0") {
                let desc = font
                    .get(b"DescendantFonts")
                    .and_then(Object::as_array)
                    .ok()
                    .and_then(|a| a.first().cloned());
                let cid = match desc {
                    Some(Object::Reference(r)) => doc.get_object(r).and_then(Object::as_dict).ok(),
                    Some(Object::Dictionary(ref d)) => Some(d),
                    _ => None,
                };
                cid.and_then(|c| c.get(b"FontDescriptor").ok())
                    .and_then(|o| o.as_reference().ok())
                    .and_then(|r| doc.get_object(r).and_then(Object::as_dict).ok())
            } else {
                font.get(b"FontDescriptor")
                    .and_then(Object::as_reference)
                    .ok()
                    .and_then(|r| doc.get_object(r).and_then(Object::as_dict).ok())
            };
            let descriptor = descriptor.expect("a text font has a resolvable /FontDescriptor");
            assert!(
                descriptor.has(b"FontFile2") || descriptor.has(b"FontFile3"),
                "a text font is not embedded (no /FontFile2 or /FontFile3)"
            );
        }
    }
}

fn find(hay: &[u8], needle: &[u8]) -> bool {
    needle.len() <= hay.len() && hay.windows(needle.len()).any(|w| w == needle)
}

fn last_startxref(pdf: &[u8]) -> Option<usize> {
    let pos = pdf.windows(9).rposition(|w| w == b"startxref")?;
    let mut i = pos + 9;
    while i < pdf.len() && pdf[i].is_ascii_whitespace() {
        i += 1;
    }
    let start = i;
    while i < pdf.len() && pdf[i].is_ascii_digit() {
        i += 1;
    }
    std::str::from_utf8(&pdf[start..i]).ok()?.parse().ok()
}

/// Assert `model` is a well-formed `DocumentModel` (§3.1): the frozen metadata keys are present
/// with the right JSON types and a non-empty, tagged `blocks` array.
fn assert_well_formed_document_model(model: &Value) {
    assert!(
        model["title"].is_string(),
        "model.title is a string: {model}"
    );
    assert!(model["entity_name"].is_string(), "model.entity_name string");
    // entity_nipc is Option<String> — present as a key (string or null).
    assert!(
        model.get("entity_nipc").is_some(),
        "model.entity_nipc key present"
    );
    assert!(model["subject"].is_string(), "model.subject is a string");
    assert_eq!(model["language"], "pt-PT", "model.language is pt-PT");
    let blocks = model["blocks"]
        .as_array()
        .expect("model.blocks is an array");
    assert!(!blocks.is_empty(), "model.blocks is non-empty");
    // Every block is self-describing (serde-tagged with a `type`).
    assert!(
        blocks.iter().all(|b| b["type"].is_string()),
        "every block carries a `type` tag: {model}"
    );
}

#[tokio::test(flavor = "multi_thread", worker_threads = 2)]
#[cfg_attr(
    not(feature = "e2e"),
    ignore = "composed-system e2e: spawns the real server binary (run with --features e2e)"
)]
async fn document_pipeline_end_to_end_and_pdfa_conformance() {
    let h = ServerHarness::start().await;
    let (token, _entity_id, book_id, act_id) = spine_up_to_signing(&h).await;

    // ----- Book opening produced a termo de abertura document (TPL-10/11) -----------------------
    // A `document.generated` event for the termo (scope has NO `act:` segment) is on the chain.
    let (status, events) = h.get_json("/v1/ledger/events").await;
    assert_eq!(status, 200);
    let events_arr = events.as_array().expect("events array");
    assert!(
        events_arr.iter().any(|e| e["kind"] == "document.generated"
            && e["scope"]
                .as_str()
                .is_some_and(|s| s.contains(&format!("book:{book_id}")) && !s.contains("/act:"))),
        "book-open emitted a termo document.generated event: {events}"
    );
    // The termo PDF is preserved + downloadable (keyed by the book id; instruments have no act).
    let (status, ctype, termo_pdf) = get_bytes(&h, &format!("/v1/acts/{book_id}/document")).await;
    assert_eq!(status, 200, "termo document downloads");
    assert!(ctype.starts_with("application/pdf"), "termo ctype={ctype}");
    assert!(termo_pdf.starts_with(b"%PDF-"), "termo bytes are a PDF");
    // The termo is itself PDF/A-2u conformant (same writer, same guarantees).
    assert_pdfa2u_conformant(&termo_pdf);

    // ----- (d) preview renders a well-formed DocumentModel PRE-seal (draft preview) --------------
    let (status, pre_model) = h
        .get_json(&format!("/v1/acts/{act_id}/document/preview"))
        .await;
    assert_eq!(status, 200, "pre-seal preview: {pre_model}");
    assert_eq!(pre_model["title"], "Ata da Assembleia Geral Anual");
    assert_well_formed_document_model(&pre_model);

    // Pre-seal the persisted PDF is 404 (nothing produced until sealing).
    let (status, _, _) = get_bytes(&h, &format!("/v1/acts/{act_id}/document")).await;
    assert_eq!(status, 404, "no persisted PDF before sealing");
    // ...and so is the bundle.
    let (status, _) = h
        .get_json(&format!("/v1/acts/{act_id}/document/bundle"))
        .await;
    assert_eq!(status, 404, "no bundle before sealing");

    // ----- Seal → the act's PDF/A-2u document is produced -----------------------------------------
    let (status, sealed) = h
        .post_json_auth(&format!("/v1/acts/{act_id}/seal"), json!({}), &token)
        .await;
    assert_eq!(status, 200, "seal: {sealed}");
    assert_eq!(sealed["act"]["state"], "Sealed");
    assert_eq!(sealed["ata_number"], 1);

    // (c) SealResponse.document carries {id, pdf_digest, template_id}.
    let doc = &sealed["document"];
    assert_eq!(doc["template_id"], "csc-ata-ag/v1", "sealed doc: {sealed}");
    assert!(doc["id"].is_string(), "sealed doc id is a string");
    let claimed_digest = doc["pdf_digest"].as_str().expect("pdf_digest string");
    assert_eq!(claimed_digest.len(), 64, "pdf_digest is 64 hex chars");

    // (a) a `document.generated` ledger event exists FOR THE ACT (scope carries `act:{id}`).
    let (status, events) = h.get_json("/v1/ledger/events").await;
    assert_eq!(status, 200);
    assert!(
        events
            .as_array()
            .expect("events")
            .iter()
            .any(|e| e["kind"] == "document.generated"
                && e["scope"]
                    .as_str()
                    .is_some_and(|s| s.contains(&format!("act:{act_id}")))),
        "the seal appended an act-scoped document.generated event: {events}"
    );

    // (b) GET /v1/acts/{id}/document returns real application/pdf bytes (200, not 404).
    let (status, ctype, pdf) = get_bytes(&h, &format!("/v1/acts/{act_id}/document")).await;
    assert_eq!(status, 200, "sealed PDF downloads");
    assert!(ctype.starts_with("application/pdf"), "ata ctype={ctype}");
    assert!(pdf.starts_with(b"%PDF-"), "ata bytes are a PDF");

    // (c) the claimed digest is the sha-256 of the actually-served bytes.
    assert_eq!(
        sha256_hex(&pdf),
        claimed_digest,
        "SealResponse.pdf_digest matches sha-256 of the served bytes"
    );

    // ----- PDF/A-2u structural conformance of the served (unsigned) bytes ------------------------
    assert_pdfa2u_conformant(&pdf);

    // (d) preview still renders a well-formed DocumentModel POST-seal.
    let (status, post_model) = h
        .get_json(&format!("/v1/acts/{act_id}/document/preview"))
        .await;
    assert_eq!(status, 200, "post-seal preview: {post_model}");
    assert_well_formed_document_model(&post_model);

    // (e) the DOC-03 bundle returns the reserved `validation_report: null` shape.
    let (status, bundle) = h
        .get_json(&format!("/v1/acts/{act_id}/document/bundle"))
        .await;
    assert_eq!(status, 200, "bundle: {bundle}");
    assert_eq!(bundle["act_id"], act_id);
    assert_eq!(bundle["document"]["template_id"], "csc-ata-ag/v1");
    assert_eq!(bundle["document"]["pdf_digest"], claimed_digest);
    assert_eq!(
        bundle["document"]["profile"],
        "application/pdf; profile=PDF/A-2u"
    );
    assert_eq!(bundle["pdf"]["media_type"], "application/pdf");
    assert_eq!(
        bundle["pdf"]["byte_length"].as_u64().expect("byte_length"),
        pdf.len() as u64,
        "bundle byte_length matches the served bytes"
    );
    assert!(bundle["attachments_manifest"].is_array());
    assert!(
        bundle["validation_report"].is_null(),
        "the DOC-03 validation-report slot is reserved for Wave D (null): {bundle}"
    );

    // (f) GET /v1/templates lists the spine templates, bare and family/stage-filtered.
    let (status, all) = h.get_json("/v1/templates").await;
    assert_eq!(status, 200);
    let all_ids: Vec<&str> = all
        .as_array()
        .expect("templates array")
        .iter()
        .map(|t| t["id"].as_str().unwrap_or_default())
        .collect();
    assert!(all_ids.contains(&"csc-ata-ag/v1"), "spine: ata template");
    assert!(
        all_ids.contains(&"csc-termo-abertura/v1"),
        "spine: termo template"
    );

    let (status, ata) = h
        .get_json("/v1/templates?family=CommercialCompany&stage=Ata")
        .await;
    assert_eq!(status, 200);
    let ata_arr = ata.as_array().expect("filtered ata templates");
    assert!(!ata_arr.is_empty(), "the ata filter returns a template");
    assert!(ata_arr.iter().all(|t| t["stage"] == "Ata"));
    assert!(
        ata_arr
            .iter()
            .any(|t| t["id"] == "csc-ata-ag/v1" && t["locale"] == "pt-PT"),
        "the CSC ata template is listed pt-PT: {ata}"
    );

    let (status, termo) = h
        .get_json("/v1/templates?family=CommercialCompany&stage=TermoAbertura")
        .await;
    assert_eq!(status, 200);
    assert!(
        termo
            .as_array()
            .expect("filtered termo templates")
            .iter()
            .any(|t| t["id"] == "csc-termo-abertura/v1"),
        "the CSC termo template is listed: {termo}"
    );

    // The chain still verifies with the document events woven in.
    let (status, verify) = h.get_json("/v1/ledger/verify").await;
    assert_eq!(status, 200);
    assert_eq!(verify["valid"], true, "ledger verifies: {verify}");
}

/// Service-level determinism (plan D3/§164): a second, independent server sealing an equivalent
/// record must produce the **same** `pdf_digest` — the writer reads no clock (`created_at` derives
/// from the frozen meeting date), so a sealed record + pinned template regenerates byte-identical
/// PDF bytes. Proven over two REAL server processes, not a unit-level shortcut.
#[tokio::test(flavor = "multi_thread", worker_threads = 2)]
#[cfg_attr(
    not(feature = "e2e"),
    ignore = "composed-system e2e: spawns the real server binary (run with --features e2e)"
)]
async fn sealed_document_digest_is_deterministic_across_servers() {
    async fn seal_and_capture_digest() -> (String, Vec<u8>) {
        let h = ServerHarness::start().await;
        let (token, _e, _b, act_id) = spine_up_to_signing(&h).await;
        let (status, sealed) = h
            .post_json_auth(&format!("/v1/acts/{act_id}/seal"), json!({}), &token)
            .await;
        assert_eq!(status, 200, "seal: {sealed}");
        let digest = sealed["document"]["pdf_digest"]
            .as_str()
            .expect("pdf_digest")
            .to_owned();
        let (status, _ctype, pdf) = get_bytes(&h, &format!("/v1/acts/{act_id}/document")).await;
        assert_eq!(status, 200);
        (digest, pdf)
    }

    let (digest_a, pdf_a) = seal_and_capture_digest().await;
    let (digest_b, pdf_b) = seal_and_capture_digest().await;

    assert_eq!(
        digest_a, digest_b,
        "the same frozen record → the same pdf_digest across two independent servers"
    );
    // And the bytes themselves are identical (determinism is byte-level, not just digest-level).
    assert_eq!(pdf_a, pdf_b, "the served PDF bytes are byte-identical");
    // The digest is genuinely the sha-256 of those bytes (not an independent field).
    assert_eq!(sha256_hex(&pdf_a), digest_a);
    // ...and the deterministic bytes are conformant.
    assert_pdfa2u_conformant(&pdf_a);
}
